### ISSUE TITLE
Tests missing

### ISSUE THREAD

**Issue by florianjehn** [allfed/water-access#4]

**Comment by florianjehn** [comment]
@jamesmulhall These are still missing? What's going on here?

**Comment by jamesmulhall** [comment]
Hi @florianjehn, we've been working on _jm_work_ for a while, which has tests for the main parts of the code. We're planning to move everything back to main for a 1.0 release after paper submission

**Comment by florianjehn** [comment]
Ah alright, did not realize that this has seperate branches. Thanks
